# Generated by Django 2.1.3 on 2018-12-01 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 7, 4, 36, 567403, tzinfo=utc)),
        ),
    ]
